zend_extension=xdebug

; -------------------------
; Core
; -------------------------
xdebug.mode=debug
xdebug.start_with_request=yes

; -------------------------
; IDE / Client
; -------------------------
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=PHPSTORM

; -------------------------
; Logging (útil para debug)
; -------------------------
xdebug.log=/tmp/xdebug.log
xdebug.log_level=0

; -------------------------
; Performance safety
; -------------------------
xdebug.max_nesting_level=512
