shared:
    resource:
        path: ../src/Shared
        namespace: App\Shared
    type: attribute

news_headlines:
    resource:
        path: ../src/NewsHeadlines
        namespace: App\NewsHeadlines
    type: attribute
